ALTER TABLE users
    ADD COLUMN IF NOT EXISTS total_xp          INT  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_streak     INT  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS longest_streak     INT  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_activity_date DATE;